language: cpp
compiler: gcc
dist: trusty

before_install:
  # C++11
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  # C++11
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90

script: 
  - g++ main.cpp -std=c++11 -o helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb
 # - ./helloworld
  deploy:
    provider: script
    skip_cleanup: true
    script:
    - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -alex-kalugin-cpp:$BINTRAY_API_KEY "https://api.bintray.com/content/alex-kalugin-cpp/Otus-cpp1/helloworld/$TRAVIS_BUILD_NUMBER/helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
